notifyTokenPurchase events
electrumpayments/prepaidutility-service-interface pull request #21
Opened 2020-08-30 18:46 UTC by eon

Adds support for a `notifyTokenPurchase` operation in a new `events` resource. The purpose of this operation is to notify implementers that successful purchase has taken place, including the purchase response details in the operation body.

##### Why is this useful?

Implementations at digital channels sometimes need to communicate token details to consumers out of band of the online purchase flow. This is especially useful when doing resubmits when the online request/response flow has already completed by the time the purchase completes. A generic mechanism for notification of the token details is thus required.

##### Why is this weird?

The system that needs to receive these new notifications and the system that does the financial message processing may not be the same system and it might thus be the case that an implementation may only need to implement the `events` and not the other resources, and will have to ensure suitable 501 statuses are returned for the unimplemented operations. Systems who do not have to implement the `events` resource may ignore the new resource (the default implementation will simply return a 501 status code). Therefore, the weirdness is merely a detail that notification implementations need to concern themselves with and relatively easily overcome, and as such it is my option that the benefits of keeping the `events` resource contained in the main prepaid utility API outweighs the limitations.

2020-08-31 06:27 UTC, TimElectrum requested changes
blah blah blah...tests...blah blah blah

2020-08-31 06:27 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/api/EventsResource.java
> +@Path(PrepaidUtilityApi.API_BASE_PATH)
I think this is how we end up duplicating the API base path. It's set here but it is also specified in the input to the swagger creation in the POM and we end up duplicating the base path in the description of the operation.
```suggestion
@Path(EventsResource.PATH)
```

Considering this is a fairly common mistake with a real impact on the published and implemented API I wonder if we should create a test for it. If so, we should probably create it in the base API so it can be implemented across our APIs.

2020-08-31 06:27 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/api/EventsResource.java
> +      public static final String PATH = EventsResource.PATH + "/tokenPurchases/{" + PathParameters.PURCHASE_ID + "}";
because all the operations for this resource start with `EventsResource.PATH` we've tended to create `FULL_PATH` and `RELATIVE_PATH` fields:
```suggestion
      public static final String RELATIVE_PATH = "/tokenPurchases/{" + PathParameters.PURCHASE_ID + "}";
      public static final String FULL_PATH = EventsResource.PATH + RELATIVE_PATH;
```

2020-08-31 06:27 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/api/EventsResource.java
> +   @Path(NotifyTokenPurchase.PATH)
since the resource path is already annotated against the whole resource we just need the relative path:
```suggestion
   @Path(NotifyTokenPurchase.RELATIVE_PATH)
```

2020-08-31 06:27 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/api/EventsResource.java
> +   @ApiOperation(nickname = NotifyTokenPurchase.NOTIFY_TOKEN_PURCHASE, value = "Notifies that a successful token purchase has taken place.", notes = "An event notification to signal that a successful
```suggestion
   @ApiOperation(nickname = NotifyTokenPurchase.NOTIFY_TOKEN_PURCHASE, value = "Notifies that a successful token purchase has taken place.", notes = "An event notification to signal that a successful token purchase was performed. This operation is for informational purposes only. Implementations that do not need to subscribe to this event may simply return an HTTP status code 501.")
```

2020-08-31 06:27 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/api/EventsResource.java
> +   public class NotifyTokenPurchase {
Sonar's complained about not making these kinds of classes `static`. I don't have strong feelings but just letting you know.

2020-08-31 06:27 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/api/EventsResource.java
> +      public static final String PATH = EventsResource.PATH + "/tokenPurchases/{" + PathParameters.PURCHASE_ID + "}";
just a vague comment on using path params vs using query params...

I'm not sure which would be the most correct for a RESTful service but, aside from that, I find query params easier to use since the order is less important and one doesn't need to _substitute_ a parameter in a string.

Since the resource `/events/tokenPurchases/{purchaseId}` doesn't technically exist but is rather being notified I think it's okay to use a query parameter instead of a path parameter.

2020-08-31 07:44 UTC, eon commented on src/main/java/io/electrum/prepaidutility/api/EventsResource.java
> +@Path(PrepaidUtilityApi.API_BASE_PATH)
Was just following the pattern here, it's the same for the other resources in this API. Better to stick with a common feel for all resources or fix the broken pattern for this resource only? I vote for keep the pattern...not sure how we will ever fix this though

2020-08-31 08:03 UTC, eon commented on src/main/java/io/electrum/prepaidutility/api/EventsResource.java
> +      public static final String PATH = EventsResource.PATH + "/tokenPurchases/{" + PathParameters.PURCHASE_ID + "}";
I don't really understand this pattern. When I look at airtime, for example, the FULL_PATH variable never gets used. What is its purpose?

Also, I don't see the FULL_PATH pattern used for other resources in ppu - it's another of those "to refactor or not to refactor" head-scratchers. I'm of the opinion that it is better to just match the existing pattern for a small addition like this.

2020-09-01 06:41 UTC, RichardFourie commented
Can we include the base path fix in this PR? It actually causes issues with load balancers which then requires you to configure a `404` as a success response code instead of just a `200` or `302`.

2020-09-02 07:50 UTC, TimElectrum requested changes
definitely some little things but we might need to chat more about the base API path issue

2020-09-02 07:50 UTC, TimElectrum commented on pom.xml
>      <swagger-maven-plugin-version>3.1.3</swagger-maven-plugin-version>
Dependabot would like you to bump the Hibernate Validator version from 5.2.2.Final to 5.3.5.Final or greater

2020-09-02 07:50 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/api/EventsResource.java
> +@Path(PrepaidUtilityApi.API_BASE_PATH)
So we fixed this in other APIs by dropping the duplication from all the resource classes. Technically that's a breaking change in the API (and it's reflected in a breaking change in the swagger) and it's definitely a breaking change within our own server implementations of the APIs. But, rather than actually bump the API major version (which would cause a lot of admin since it changes the service URL) we highlight it quite explicitly in the release notes i.e. that it's a breaking change but the major version doesn't change. You can check [v1.6.0 and v1.5.0 of the SUV API](https://electrumpayments.github.io/suv-service-interface-docs/specification/release-notes/)

2020-09-02 07:50 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/api/EventsResource.java
> +@Path(PrepaidUtilityApi.API_BASE_PATH)
also, this seems to be causing a nuisance for some customers so we should fix this as suggested if possible rather than kicking the can down the road a little bit further.

2020-09-02 07:50 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/api/EventsResource.java
> +      public class PathParameters {
gah! Since you changed this bit of code since my last comment, Github won't let me continue the conversation because it thinks it's outdated!

I wanted to say that you gave my path vs query parameter comment a 👍  but this is still called `PathParameters`. Then I noticed that you dropped it from the actual path so maybe you just forgot to rename this inner class?

2020-09-02 07:50 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/api/EventsResource.java
> +      public static final String PATH = EventsResource.PATH + "/tokenPurchases";
to recap a previous conversation:

Tim:
> because all the operations for this resource start with EventsResource.PATH we've tended to create FULL_PATH and RELATIVE_PATH fields:
```suggestion
      public static final String RELATIVE_PATH = "/tokenPurchases/{" + PathParameters.PURCHASE_ID + "}";
      public static final String FULL_PATH = EventsResource.PATH + RELATIVE_PATH;
```

Eon:
> I don't really understand this pattern. When I look at airtime, for example, the FULL_PATH variable never gets used. What is its purpose?
>
>Also, I don't see the FULL_PATH pattern used for other resources in ppu - it's another of those "to refactor or not to refactor" head-scratchers. I'm of the opinion that it is better to just match the existing pattern for a small addition like this.

Since the `@Path` annotation defines the location of the entire resource class, I started adding the `RELATIVE_PATH` field because we needed to append something to each specific operation within the resource. I.e. `RELATIVE_PATH` is the location of the specific operation relative to the resource.

`FULL_PATH` was then provided as a courtesy to anyone who wanted it and it would then provide the path from the API base path to the specific operation. You're right though, we don't actually use it. But I still think it's a clear enough description of what it is and it's easy enough to implement that we can keep doing it. Although, since I don't know of anyone actually using it, maybe we keep doing it just to maintain the status quo rather than to help solve a known problem.

2020-09-02 07:50 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/api/IEventsResource.java
> +      asyncResponse.resume(new ServerErrorException("This operation has not been implemented.", 501));
```suggestion
      throw new UnsupportedOperationException("This operation has not been implemented.");
```

Both of these will result in an HTTP 501 being returned to the client. But calling `asyncResponse.resume` forces that response without the implementing class having the opportunity to intercept it.

I think throwing the exception provides better transparency to the implementer who can catch it and handle it in some other way if desired.

I made [the same comment](https://github.com/electrumpayments/airtime-service-interface/pull/61#discussion_r481814688) for @gevashkar-rampersadh who's adding a new operation to the Airtime API. I seem to be outnumbered now though so perhaps I need to consider I'm wrong 😨 

Thoughts?

2020-09-02 13:24 UTC, eon commented on src/main/java/io/electrum/prepaidutility/api/IEventsResource.java
> +      asyncResponse.resume(new ServerErrorException("This operation has not been implemented.", 501));
I think it let's stick with it as-is. Like @gevashkar-rampersadh said, the implementer of `IEventsResource` has control either way and the original implementation's effect is a bit clearer to any reader. What you say does apply to EventsResource, but we are not really expecting any interception there are we?

2020-09-02 14:40 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/api/IEventsResource.java
> +      asyncResponse.resume(new ServerErrorException("This operation has not been implemented.", 501));
I was thinking more about cases where a new method is provided with a `default` implementation. If someone had already implemented the interface before the `default` method existed they'd never know to intercept the new method. But I think an implementer is more likely to spot that something's changed if they're catching exceptions so throwing an exception rather than actually returning an HTTP 501 on behalf of the implementer would make the change more obvious.

Well, that was my thinking but I'm less convinced now.

2020-09-02 14:44 UTC, TimElectrum approved these changes
happiness

2020-09-02 14:44 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/api/EventsResource.java
> +public abstract class EventsResource {
do you feel like adding a `@since` annotation in some class level javadoc so it's easier to spot which this comes from in subsequent development?

2020-09-02 15:21 UTC, merged