Feature notify token purchase
electrumpayments/prepaidutility-service-interface pull request #22
Opened 2020-09-08 12:54 UTC by MNS003

Hey there,

Here's an awesome PR with some minor additions to how we build http messages.

Lemme know what you think.

2020-09-17 14:40 UTC, TimElectrum requested changes
please also update the `README.md` in the project's base directory

2020-09-17 14:40 UTC, TimElectrum commented on release-notes.md
> +# Prepaid Utility Service Interface Release Notes
release notes for our public APIs live here: https://github.com/electrumpayments/prepaidutility-service-interface/blob/master/src/docs/devguide/hugo/site/content/release-notes.md

Note the slightly different formatting compared to our internal release notes.

you can remove this page.

2020-09-17 14:40 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/model/ErrorDetail.java
> +       * @since 3.10.1
you sure that's the right version?

2020-09-17 14:40 UTC, TimElectrum commented on pom.xml
> +    <patch-version>0-SNAPSHOT</patch-version>
don't forget to drop `-SNAPSHOT`

2020-09-18 05:26 UTC, MNS003 commented on release-notes.md
> +# Prepaid Utility Service Interface Release Notes
Awe, I didn't know that... Thanks.

2020-09-18 05:27 UTC, MNS003 commented on src/main/java/io/electrum/prepaidutility/model/ErrorDetail.java
> +       * @since 3.10.1
I am now

2020-09-18 06:14 UTC, TimElectrum requested changes

2020-09-18 06:14 UTC, TimElectrum commented on src/main/java/io/electrum/prepaidutility/model/ErrorDetail.java
> +      NOTIFY_TOKEN_PURCHASE("NOTIFY_TOKEN_PURCHASE");
the `ModelTests` class in the test classes has a test to ensure the ordinal values of the `TokenTypeEnum` enumerations doesn't change. Please can you add a similar test for these `RequestType` enumerations.

2020-09-18 06:18 UTC, MNS003 commented on src/main/java/io/electrum/prepaidutility/model/ErrorDetail.java
> +      NOTIFY_TOKEN_PURCHASE("NOTIFY_TOKEN_PURCHASE");
Awe, no problem.

2020-09-18 06:39 UTC, TimElectrum approved these changes

2020-09-18 06:42 UTC, merged